### ISSUE TITLE
Generate sample JS code based on OData query

### ISSUE THREAD

**Issue by shytikov** [Innofactor/FetchXMLBuilder#103]
We already have sample C# code generated, based on query composed, but since `OData` feature was added recently, it would be really nice to be able see example JS code generated too.

It would help casual CRM developer a lot!

I think it could be additional options, like use `jQuery` for sending request, or reuse bare `JS` objects.

**Comment by pieeetr** [comment]
Sounds incredible :-)

**Comment by rappen** [comment]
You are very welcome to contribute :)
Do you have an example of code snippet you would like to get?
