### ISSUE TITLE
Allow copy column name / friendly name from result grid

### ISSUE THREAD

**Issue by shytikov** [Innofactor/FetchXMLBuilder#109]
It would be nice to have ability copy conumn name / friendly name from result grid with the right mouse click.

**Comment by rappen** [comment]
I was hoping this property would accomplish that...
![image](https://cloud.githubusercontent.com/assets/2572253/12949235/135224c6-d007-11e5-8cb6-dba46065599b.png)

Apparently not. Any clues?

**Comment by rappen** [comment]
#132
