### ISSUE TITLE
Allow editing records in Result Grid

### ISSUE THREAD

**Issue by shytikov** [Innofactor/FetchXMLBuilder#110]
Yes, I know it's very dangerous, but so cool and useful!

**Comment by rappen** [comment]
I don't think I can design a ``disclaimer-you-are-on-your-own-we-take-no-responsibility-sign`` big enough, users might need a 4K screen... but you never know....! ;)

**Comment by shytikov** [comment]
But we can have setting in `Options` like, enable grid editing. And it will be disabled by default.

**Comment by katzenbe** [comment]
This sounds dangerous and complicated, I would not use it.

**Comment by shytikov** [comment]
I would rather say, that for real dangerous stuff CRM bans by default, and you just cannot do it, but everything that is supported by regular `Update` call is relatively safe, but might lead to inconsistencies.

I'm talking about following scenarios in scope of this task: you want to change value in the field not shown on form. To be able to do this normally you would do following:

* Add field on form;
* Publish form customization;
* Change value of the field;
* Verify that change did achieved planned result;
* Remove field from form;
* Publish form customization;

It's take a time and two publishes could affect users if they are currently logged in. I think with `FXB` it could be done more easily.

**Comment by polshgiant** [comment]
@shytikov With the handy edit in Excel feature introduced online last year, you can simply add the field to a view, export to Excel (in browser), edit, then click the Save Changes to CRM button (or whatever the button is called).  Definitely less painful than the old method you describe, but still not as sweet as it would be if FXB allowed editing!
