### ISSUE TITLE
Allow Bulk Delete from FXB

### ISSUE THREAD

**Issue by rajyraman** [Innofactor/FetchXMLBuilder#113]
This is currently not a core operation of FXB. But IMHO, this would be best done in FXB, rather than developing a new tool for it. CRM OOB doesn't seem to be supporting bulk deletes that have a outer join, similar to Advanced Find. It would be nice if there is a button to trigger bulk delete with the specified fetchxml. The downside is that some people would be burnt by the ease of deletion. For admins and people who know what they are doing, this would be a nice feature. 

You probably can hide this behind a flag that has to be enabled to display advanced features. In the future you can use this to expose functionalities that use the generated fetchxml to perform operations against CRM. Currently I cannot think any other use case other than bulk delete, but there could be others.

**Comment by rappen** [comment]
Interresting idea, related to #110

**Comment by rappen** [comment]
Better to develop a separate Bulk Delete tool for XTB, and integrate with FXB to compose the query to find records to delete.
[CRMWinForm](https://www.nuget.org/packages/Cinteros.Xrm.CRMWinForm/) package can be used to display target records, and possibly select a subset to delete.
