### ISSUE TITLE
Tooltips in GridView

### ISSUE THREAD

**Issue by shytikov** [Innofactor/FetchXMLBuilder#134]
It would be nice to have tooltips of the `GridView` headers will display attribute label if headers are showing physical name of an attribute. And vice versa — if headers are showing labels, physical name should be in tooltip.

Sometimes several different field can have same labels, and it would be nice to distinguish between them at least by pointing on them and waiting for tooltip.

**Comment by rappen** [comment]
Issue moved to [Innofactor/CRMWinForm #7](https://github.com/Innofactor/CRMWinForm/issues/7) via [**ZenHub**](https://www.zenhub.com/)
