### ISSUE TITLE
Cannot save view. Returned attributes must not be changed.

### ISSUE THREAD

**Issue by bryce2071** [Innofactor/FetchXMLBuilder#139]
Hi jonas, 

i thought i could use the tool to do Things like remove cols from view fastly, but if i do that, the above error Comes.

What does this error mean?
If i remove a col, the Attributes Needs to be updated, or?

thx, greets Pit

**Comment by rappen** [comment]
Hi Bryce
FXB only updates the query of the view, which means that the query must contain the expected set of columns, otherwise the view will "crash".
You could try the View Designer plugin from the Plugin store to change columns :)
![image](https://cloud.githubusercontent.com/assets/2572253/17396741/0fdf1020-5a35-11e6-89bc-b079894cb16d.png)

**Comment by mscottsewell** [comment]
Can confirm. - The View Designer + FXB is a powerful combo!
(Now if only the View Designer would let you 'preview' the data in the grid....  :shipit: )

**Comment by rappen** [comment]
@shytikov - When do we get data preview...? ;)
https://github.com/Innofactor/XrmToolBox.ViewDesigner/issues/1

**Comment by shytikov** [comment]
Hi,

I've just uploaded code for Innofactor/XrmToolBox.ViewDesigner#1. After build and upload to `NuGet` you can get update from plugin store.

**Comment by rappen** [comment]
And the View Designer is now built and published.
Available in the XTB Plugin Store, version 1.2016.8.6.

**Comment by mscottsewell** [comment]
@shytikov  I've given it a try - and for some reason it's only displaying data in a handful of the columns in the view - it appears that it's only the record's "name" field and then the value from related 'lookup' fields. - but optionsets, text, dates, money, decimal - these fields are all "blank".

**Comment by shytikov** [comment]
I got it, will check the code and push fix for the issue. Probably will need Jonas to trigger the build, but I'm pretty sure we can quickly come back to you with proper binary!

**Comment by shytikov** [comment]
@mscottsewell you can check most recent sources, and hopefully Jonas will help me upload newest package to `NuGet` as well...

**Comment by rappen** [comment]
It is now built and available in Plugin Store!

**Comment by mscottsewell** [comment]
This is really improving - however, I'm still seeing blanks for decimal and whole number fields. (currency, string, lookup, date and optionsets all look ok.)

[I'll add these as separate 'issues']
Also - it would be nice to not require that I re-select the entity each time to view a different view within the entity - (I'm looking to check changes across multiple views of my data and it's annoying to keep re-typing the entity name just to select a different view within the same entity as I'm currently viewing.)
Also- any chance you could allow us to move to the next page of results?-  currently I only see the first 50 or so and would like to validate that the view looks good for more than just that sample.)

**Comment by rappen** [comment]
Checking old threads....
Is this issue ready to be closed, or is anything still missing?
Ping @bryce2071 @mscottsewell @shytikov

**Comment by bryce2071** [comment]
Can be closed

--
Gruss
Peter Bohn




On Wed, Sep 21, 2016 at 2:23 PM +0200, "Jonas Rapp" <notifications@github.com> wrote:












Checking old threads....

Is this issue ready to be closed, or is anything still missing?

Ping @bryce2071 @mscottsewell @shytikov
