### ISSUE TITLE
Retrieving Hierarchical data not supported

### ISSUE THREAD

**Issue by piyushpaliwal** [Innofactor/FetchXMLBuilder#141]
With recent changes in CRM, a lot of new operators have been built especially related to Hierarchical data; I can't seem to find that they are incorporated in this tool.

Operators like Above, Under, etc. Correct me if I'm wrong here

[https://msdn.microsoft.com/en-in/library/dn817893.aspx](https://msdn.microsoft.com/en-in/library/dn817893.aspx)

**Comment by rappen** [comment]
It does work, but only if the condition attribute is a uniqueidentifier:

![image](https://cloud.githubusercontent.com/assets/2572253/18049081/4b52a3be-6de6-11e6-80df-3d3df691036f.png)

**Comment by piyushpaliwal** [comment]
hmm .. I kind of missed that, thanks for the quick clarification.
