### ISSUE TITLE
FetchXML Builder CRM 2011

### ISSUE THREAD

**Issue by kiquenet** [Innofactor/FetchXMLBuilder#145]
FetchXML Builder not Works for CRM 2011 ? I get an error 
The error is:

> The formatter threw an exception while trying to deserialize the message
> 
> There was an error while trying to deserialize parameter 
> http://schemas.microsoft.com/xrm/2011/Contracts/Services:request
> 
> The InnerException message was 'Error in line 1 position 456. 
> Element 'http://schemas.microsoft.com/xrm/2011/Contracts/Services:request' 
> contains data of the type that maps to the name
> http://schemas.microsoft.com/xrm/2011/Contracts:RetrieveMetadadaChangesRequest
> 
> The deserializer has no knowledge of any type that maps to this name.
> Consider changing the implementation of the ResolveName method on your DataContractResolver to return a non-null value for name
> RetrieveMetadadaChangesRequest and namespace http://schemas.microsoft.com/xrm/2011/Contracts
> Please see InnerException for more details

**Comment by rappen** [comment]
Could you provide more details? At what stage do you get this, what were you trying, were you connected, what type of query etc?
I just tried a 2011 instance, without problems.

**Comment by rajyraman** [comment]
Maybe the CRM SDK dlls are registered in the GAC?

**Comment by kiquenet** [comment]
Not SDK dlls in GAC.

I get error when I try select a Entity Name.

**Comment by rappen** [comment]
What version of XrmToolBox (visible in title bar) and FetchXML Builder (click the About button in top right corner) do you use?

**Comment by maeg02** [comment]
If you have a CRM 2011 version prior to Update Rollup 12, this metod is not supported: https://msdn.microsoft.com/en-us/library/jj863599(v=crm.5).aspx and the error is then showing up directly loading the plugin

**Comment by rappen** [comment]
Aouch.... pre 2011 UR12.... Didn't see that one coming.

**Comment by maeg02** [comment]
I'm not sure if this is worth fixing, or its better to say, 2011 UR 18, in this page instead: http://www.xrmtoolbox.com/AboutXTB.html
