### ISSUE TITLE
Getting an error with the latest update 1.2016.12.115

### ISSUE THREAD

**Issue by piyushpaliwal** [Innofactor/FetchXMLBuilder#154]
Hi,
upon launching this, immediately an error is thrown which reads following

---------------------------
Error
---------------------------
An error occured when trying to display this plugin: Method not found: 'Void XrmToolBox.Extensibility.PluginControlBase.LogInfo(System.String, System.Object[])'.
---------------------------
OK   
---------------------------

Can you please investigate it what went wrong there? Also, is there any way I can go to the previous version of plugin?

**Comment by rappen** [comment]
There is nothing wrong - just make sure you have the latest version of XrmToolBox.
Requires 1.2012.11.3 or later.

**Comment by rappen** [comment]
Sorry, it should be XTB 1.2016.11.3 or later.

**Comment by silgenfritz** [comment]
Having same issue.
![image](https://cloud.githubusercontent.com/assets/8113362/21262223/24c4bfe8-c35e-11e6-941a-d98e9622e066.png)
![image](https://cloud.githubusercontent.com/assets/8113362/21262236/4106bdf0-c35e-11e6-9be8-657da9fe1e1e.png)

**Comment by rappen** [comment]
@silgenfritz can you verify that you have version ``1.2016.11.3`` or later of XrmToolBox ?
My plugins usually require latest&greatest existing version of XTB.

**Comment by silgenfritz** [comment]
![image](https://cloud.githubusercontent.com/assets/8113362/21286747/3ed9ef1c-c42a-11e6-9b47-18bb0afd1895.png)

**Comment by silgenfritz** [comment]
Missed it by that much....
I have version 1.2016.10.2.  Your really are bleeding edge they are only at 1.2016.11.4 now.

Thanks

**Comment by rappen** [comment]
That's how I like it ;)
