### ISSUE TITLE
Can't select Group by/Aggregate option 

### ISSUE THREAD

**Issue by ankita2211** [Innofactor/FetchXMLBuilder#155]
Hi,

![111](https://cloud.githubusercontent.com/assets/24587865/21225420/d1c46f44-c2f6-11e6-94d8-73ca0a528e02.png)
Please refer above screenshot, we can not select group by and aggregate option. So please help me or suggest me what i do next.

**Comment by rappen** [comment]
If you select the ``fetch`` node, you can specify it should b ean aggregate query.
That will enable aggregate-only attributes in the rest of the query nodes.

![image](https://cloud.githubusercontent.com/assets/2572253/21241062/5366d426-c30e-11e6-8953-06dbed255254.png)

**Comment by rappen** [comment]
Closing with no feedback. Feel free to reopen if problem persists.
