### ISSUE TITLE
Error occured when trying to display this Plugin

### ISSUE THREAD

**Issue by maustin949** [Innofactor/FetchXMLBuilder#156]
![2017-01-03_14h54_13](https://cloud.githubusercontent.com/assets/8359696/21626257/f239f5c8-d1c4-11e6-900a-0958d799af70.png)

**Comment by weharc** [comment]
I get this problem also, latest release. 1.2016.12.115 on Windows 10 Insider Preview. Kind of a showstopper.

**Comment by rappen** [comment]
Please use latest version of XrmToolBox, it requires version 1.2016.11.3 or later.
