### ISSUE TITLE
Error occurred: could not load file or assembly

### ISSUE THREAD

**Issue by advocace** [Innofactor/FetchXMLBuilder#168]
Receiving error when I try to use FetchXML Builder: Could not load file or assembly 'McTools.Xrm.Connection, Version=1.2017.1.8...'.  In XrmToolBox.exe.config the block of code for McTools is uncommented yet no joy.  What would you suggest to do next?
![fetchxmlbuilder_error_20170212](https://cloud.githubusercontent.com/assets/25729929/22866938/9dc3028e-f143-11e6-9ea2-fccc56caac22.png)

**Comment by rappen** [comment]
Hi - I notice you are running a version of XrmToolBox from October (1.2016.10.2)
FetchXML Builder works best with latest version of the toolbox, to benefit from latest features.
Could you try to update XTB and see if the problem persists?

**Comment by rappen** [comment]
No more feedback after providing explanation, closing the issue. Please reopen if you find it necessary.
