### ISSUE TITLE
FetchXML only returning first page of 5000 records

### ISSUE THREAD

**Issue by nzhome** [Innofactor/FetchXMLBuilder#169]
There are two problems, 

one is I can return the 5000 records in 1 second.   so if its so fast, why can't I return the other 6000 records too? Can you please make it return ALL pages of the fetch query results? or add a button to download another page of data, i.e. the 2nd page of 5000 records.

the other problem is that when I copy and paste the 5000 records to excel, I lose the headings, and I have to re-type them one by one, and when I have 30 fields, it takes a long time each time.  it only takes me 1 second to paste the data to excel,  but typing the field names takes ages, and could lead to some mistakes.

**Comment by nzhome** [comment]
I am confused, what is a paging cookie.  the best I could come up with is this..

<cookie page="1"><listmemberid last="{E1B03485-0000-0000-0000-00155D107003}" first="{A74C877A-0000-0000-0000-00155D107003}" /></cookie>

**Comment by rappen** [comment]
Hi nzhome

I assume you tried this setting and it still does not retrieve all pages?

![image](https://cloud.githubusercontent.com/assets/2572253/22873895/28055a80-f1c3-11e6-9592-36af4cb3821b.png)

I googled it for you, the documentation on FetchXML and a link to sample with Paging Cookie is described here: https://msdn.microsoft.com/en-us/library/gg328332.aspx

Column headers not copied is reported in issue #132.

**Comment by rappen** [comment]
No more feedback after providing explanation, closing the issue. Please reopen if you find it necessary.
