### ISSUE TITLE
Pressing 'F5' runs FetchXml from first tab - not current tab

### ISSUE THREAD

**Issue by r-weisser** [Innofactor/FetchXMLBuilder#172]
When using multiple Tabs of the same plugin hitting F5 the query of the first tab is executed.
It even gets executed if the current tab is not a  FetchXmlBuilder but a MetaDataBrowser.

Not sure if this is a bug in plugin or XrmToolBox generally.

**Comment by rajyraman** [comment]
Can confirm - Same behaviour. But, I didn't realise that you could have two instances of FXB open.

**Comment by rappen** [comment]
You can have n instances of n plugins open at the same time, and connected to n organizations :)
This is a know issue in XrmToolBox. See related issues:
https://github.com/MscrmTools/XrmToolBox/issues/479
https://github.com/Innofactor/PluginRegistration/issues/8
https://github.com/Innofactor/PluginRegistration/issues/25

And yes, very annoying and a generic solution for this would be greatly appreciated :)

**Comment by rappen** [comment]
Implement ``IShortcutReciever`` introduced by https://github.com/MscrmTools/XrmToolBox/issues/479.
