### ISSUE TITLE
How to use FetchXml to QueryExpression Converter from XrmToolBox? 

### ISSUE THREAD

**Issue by AshV** [Innofactor/FetchXMLBuilder#182]
I have seen https://github.com/Innofactor/FetchXMLBuilder/blob/master/FetchXmlBuilder/AppCode/QueryExpressionCodeGenerator.cs code but, where its can be used from UI

**Comment by rappen** [comment]
In FXB, select Save - C# - QueryExpression...
![image](https://user-images.githubusercontent.com/2572253/30784814-a8ea52ce-a15c-11e7-8a99-b34628229626.png)
