### ISSUE TITLE
Table Grid - Copy/Paste

### ISSUE THREAD

**Issue by DiggaTheWolf** [Innofactor/FetchXMLBuilder#185]
It would be nice to be able to have the displayed column headers included when copy/pasting from the result grid.

**Comment by rappen** [comment]
New option in the result grid window:

![image](https://user-images.githubusercontent.com/2572253/31795445-14561b24-b526-11e7-91b9-f41a41279fcd.png)

**Comment by DiggaTheWolf** [comment]
Awesome, thank you so much.
