### ISSUE TITLE
Systemuserid is not retrieved.

### ISSUE THREAD

**Issue by chaffee007** [Innofactor/FetchXMLBuilder#188]
When I choose UserSettings entity for fetchxml, it will retrieve other attributes but not the Guid for systemuserid.

**Comment by rappen** [comment]
Would be great with more info in your issue, but I am guessing a bit here 😃 

If you include the ``systemuserid`` column it will be returned.
```
<fetch>
  <entity name='usersettings' >
    <attribute name='systemuserid' />
    <attribute name='entityformmode' />
    <attribute name='isguidedhelpenabled' />
    <attribute name='visualizationpanelayout' />
    <attribute name='incomingemailfilteringmethod' />
  </entity>
</fetch>
```
![image](https://user-images.githubusercontent.com/2572253/33678199-57e013bc-dabb-11e7-9fe8-3c93483f2827.png)


Maybe the option for the result grid window is not checked?

![image](https://user-images.githubusercontent.com/2572253/33678077-0ce59d50-dabb-11e7-88d7-92f17fbc2a51.png)

If so, this is realted to #179

**Comment by chaffee007** [comment]
That was it.  Thanks much for your response!

[cid:image001.jpg@01D36F6E.11101A30]

Mark Chaffee
CRM Technical Analyst | Opus Holding, L.L.C.
10350 Bren Road West | Minnetonka, MN 55343
D: 952.656.4786
Mark.Chaffee@opus-group.com<mailto:Mark.Chaffee@opus-group.com> | www.opus-group.com<https://www.opus-group.com>

[cid:image002.png@01D36F6E.11101A30]<https://twitter.com/theopusgroup>  [cid:image003.png@01D36F6E.11101A30] <https://www.linkedin.com/company/10674>   [cid:image004.png@01D36F6E.11101A30] <http://www.youtube.com/user/TheOpusGroupUS>   [cid:image005.png@01D36F6E.11101A30] <https://www.opus-group.com/OurNews/EmailSubscription?utm_source=website&utm_medium=email-signature&utm_campaign=sign-up-email-sig>
