### ISSUE TITLE
Aggregate queries not working

### ISSUE THREAD

**Issue by rappen** [Innofactor/FetchXMLBuilder#191]
A simple query like this does not generate correct results:
```
<fetch aggregate='true' >
  <entity name='contact' >
    <attribute name='contactid' alias='Count' aggregate='count' />
  </entity>
</fetch>
```
It seems to be converted to ``QueryExpression`` and strip the aggregate parts.

**Comment by rappen** [comment]
Aggregate verification not executed properly in 2018 update, and SDK simply removes aggregate information from the query when converting to ``QueryExpression``.

**Comment by joshpainter** [comment]
So does FXB just no longer support aggregate queries then? Or is this going to be fixed?

**Comment by rappen** [comment]
It is fixed for next release, and available now in this beta release:
https://github.com/Innofactor/FetchXMLBuilder/releases/tag/untagged-3c93528c14ce5f68b3c9


Jonas Rapp

[Innofactor signaturlogga]

**Comment by joshpainter** [comment]
Apologies, I misread your commit comment above and deleted my post. I downloaded the latest beta, and the issue is indeed fixed! Thank you!
