### ISSUE TITLE
Include Column Headers when copying grid

### ISSUE THREAD

**Issue by craigseymour** [Innofactor/FetchXMLBuilder#192]
When you copy a the output as 'grid' it only brings across the data cells, not the headings.  It should bring over the names as displayed across the top of the grid

**Comment by rappen** [comment]
Hi Craig, did you try this?

![image](https://user-images.githubusercontent.com/2572253/35011064-3d2ba47c-fb05-11e7-9080-fca74995bbf8.png)

Implemented from issue #185

**Comment by craigseymour** [comment]
@rappen yes **of course** I checked that my plugin was updated before putting the feature request in

<hangs head in shame/>

That checkbox is exactly what I wanted.  Thank you :-)
