### ISSUE TITLE
Join together multiple FetchXml results

### ISSUE THREAD

**Issue by larmccoy** [Innofactor/FetchXMLBuilder#193]
I sometimes find that it would be useful to be able to combine results from different FetchXml queries, to allow for some types of "joins" that CRM does not permit.  For example, I have two text columns on different entities which I want to join together, but I cannot do this "join" in CRM because they are not part of a relationship between entities.  I realize that this is not optimal and correct design, but I find it happening frequently in data integration scenarios where we are sychronizing data between CRM and another external system.
I'm not too concerned with performance, since I realize that you would need to execute the two (or MORE) FetchXml queries and load all results and then join them on the client.  I would anticipate using this tool for diagnostics and data mining.
I would be willing to help work on this feature.

**Comment by rajyraman** [comment]
You can do joins on unrelated entities. You just have to specify the from/to entity and from/to attribute.

**Comment by rappen** [comment]
Agree with @rajyraman this it quite possible, even if you cannot do it in the CRM UI.
If you still want to pursue the "coded join" approach, you could easily do that by just executing two queries and then append them together:
```
    var result1 = Service.RetrieveMultiple(new QueryExpression(firstquery));
    var result2 = Service.RetrieveMultiple(new QueryExpression(secondquery));
    result1.Entities.AddRange(result2.Entities);
```

**Comment by rappen** [comment]
@larmccoy Can we close this issue, if suggested code approach above is good enough?
I don't really see this feature in FXB...

**Comment by larmccoy** [comment]
Sure. This can be closed. I wasn't aware that one could join unrelated entities in FetchXml. 
Even so, the code approach above should use Join rather than AddRange.
