### ISSUE TITLE
Enhancement: option to produce minimized fetchXml

### ISSUE THREAD

**Issue by daggen** [Innofactor/FetchXMLBuilder#197]
Great tool. Loving the new UI.
It would be great if there was a checkbox in the FetchXml view to return minimized XML.

Thanks

**Comment by rappen** [comment]
Interesting idea! I think...
How do you mean "minimized"?

**Comment by rajyraman** [comment]
Probably linearize the xml i.e no carriage returns, tabs or comments. Whole xml is in one line. I usually do this using notepad++.

**Comment by rappen** [comment]
You've got it!
Next release, I hope.

**Comment by daggen** [comment]
Great, thanks
