### ISSUE TITLE
Process (workflow) entity not available

### ISSUE THREAD

**Issue by tpickles1984** [Innofactor/FetchXMLBuilder#199]
I was looking to load a view of "Activated Processes", make some amendments, and save it back to the Dynamics 365 instance. I was able to query the workflow entity directly, but when I tried to load a view from the CRM, the "workflow" entity did not appear in the list. I went to the options and ensured that "all entities" was checked, but it still didn't show. Is this not available currently?

Many thanks

**Comment by rappen** [comment]
Sorry about very late response here...

I can see workflow entity and one view when I select **Open View** in FXB:
![image](https://user-images.githubusercontent.com/2572253/38336358-d2d7f950-3861-11e8-8704-e0834259c25c.png)

Note that if you have selected **Friendly Names** in options it will display as entity **Process**:
![image](https://user-images.githubusercontent.com/2572253/38336396-f1ff126e-3861-11e8-86e8-ab4683ae1970.png)

Please verify this and close this issue if it works, or supply additional information for the investigation! :)
