### ISSUE TITLE
Height of TreeBuilder is not restored properly

### ISSUE THREAD

**Issue by rappen** [Innofactor/FetchXMLBuilder#200]
The Properties panel below the treeview is minimized or smaller than last session.
Some numbers need to be handled better.

**Comment by ilyasgndz** [comment]
@rappen if you mean the Quick actions and Node properties section, I have same issue after XrmToolBox upgrade to version 1.2018.3.21. Each time I open fetchxmlbuilder I have to drag the quick action section up.

**Comment by rappen** [comment]
@ilyasgndz exactly what I mean. There is something with the new layout causing this, I will try to find a solution for it in next update of FXB.
