### ISSUE TITLE
Handling of OData view selection requires fix

### ISSUE THREAD

**Issue by WhiteyC** [Innofactor/FetchXMLBuilder#204]
Exception handling required when selecting OData view if linked entities exist.

![xrmtoolbox_odata_view_error](https://user-images.githubusercontent.com/23065270/38283876-d09ad29a-37fb-11e8-84c8-c1a3228344c0.PNG)

**Comment by rappen** [comment]
Ouch. That's ugly. Will fix.

Does it crash and exit, or are you able to continue work using the Continue button?

**Comment by WhiteyC** [comment]
You can continue however that error dialog continues to appear until you restart XrmToolBox application.
