### ISSUE TITLE
Show datetime with local time

### ISSUE THREAD

**Issue by rappen** [Innofactor/FetchXMLBuilder#210]
Add option in result grid to display datetime values in local time.

**Comment by Oztrea** [comment]
Hi,

I noticed that DateTime on linked entity are in UTC Time even if the check box "Show Local Time" is checked, the Raw data view shows the correct value.

**Comment by rappen** [comment]
Thanks @Oztrea for reporting this, created an issue in the CRMWinForm repository where the result grid view is developed.
