### ISSUE TITLE
Does not allow doubleclicks in GridResult in case if entity does not have form

### ISSUE THREAD

**Issue by shytikov** [Innofactor/FetchXMLBuilder#51]
It is possible to query "system" entities that does not really have an entity form. For example, `plugin`, `plugintype`, `sdkmessageprocessingstep` and others. But by showing results of such a query in the GridResult will lead to ability user to double-click on the line and open website on the address that shows nothing except confusing error message that access is denied or entity does not exist.

Both this statements are not true.

I think it's much more correct to just remove this action (and tooltip that proposes to use this functionality) from the results on entities that could not be shown on web.

**Comment by rappen** [comment]
Any clue how to distinguish these entities?
Is this available through metadata?
I really don't want to maintain a list of unavailable entities, as the platform expands.

**Comment by shytikov** [comment]
So far best guess I have is to ask platform about all `SystemForm` for given `ObjectTypeCode`...

I don't know is it possible to have `UserForm` for entity that does not have `SystemForm`?

**Comment by rappen** [comment]
Closing as the need is not obvious. Reopen if necessary.
